name: CMake on multiple platforms

on:
  push:
    branches: [ "ng" ]
  pull_request:
    branches: [ "ng" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        os: [ubuntu-latest]
        build_type: [Release]
        c_compiler: [gcc, clang]

    steps:
    - uses: actions/checkout@v4

    - name: Prepare build env
      id: env
      shell: bash
      run: >
        sudo apt-get update && sudo apt-get install -y
        libx11-dev libxt-dev libsx-dev libreadline-dev libcairo2-dev libfreetype-dev
        libgeotiff-dev libtiff-dev libgd-dev libshp-dev libgrib2c-dev

    - name: Set reusable strings
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    - name: Configure CMake
      run: >
        cmake -B ${{ steps.strings.outputs.build-output-dir }}
        -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        -S ${{ github.workspace }}

    - name: Build
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }}

    - name: Test
      working-directory: ${{ steps.strings.outputs.build-output-dir }}
      run: ctest --build-config ${{ matrix.build_type }}
