name: CMake on multiple platforms

on:
  push:
    branches: [ "ng" ]
  pull_request:
    branches: [ "ng" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true

      matrix:
        distro:
          # - ubuntu:18.04  # Went EOL on 31 May 2023, GitHub Actions no longer supports this
          - ubuntu:20.04
          - ubuntu:22.04
          - ubuntu:24.04
        build_type: [Release]
        c_compiler: [gcc]

    container: ${{ matrix.distro }}

    steps:
    - uses: actions/checkout@v4

    - name: Prepare build env
      id: env
      shell: bash
      run: |
        export DEBIAN_FRONTEND=noninteractive
        case "${{ matrix.distro }}" in
          ubuntu:*)
            apt-get update && apt-get install -y --no-install-recommends \
              build-essential gcc g++ cmake \
              libx11-dev libxt-dev libsx-dev libreadline-dev libncurses-dev libcairo2-dev \
              libgeotiff-dev libtiff-dev libgd-dev libshp-dev \
              libudunits2-dev libhdf4-dev libhdf5-dev libnetcdf-dev \
              libdap-dev libgadap-dev
        esac

        case "${{ matrix.distro }}" in
          ubuntu:24*)
            apt-get update && apt-get install -y --no-install-recommends \
              libg2c-dev libfreetype-dev
              ;;
          ubuntu:20*|ubuntu:22*)
            apt-get update && apt-get install -y --no-install-recommends \
              libgrib2c-dev libfreetype-dev
              ;;
          ubuntu:18*)
            apt-get update && apt-get install -y --no-install-recommends \
              libgrib2c-dev libfreetype6-dev
              ;;
        esac

    - name: Set reusable strings
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=$GITHUB_WORKSPACE/build" >> "$GITHUB_OUTPUT"

    - name: Configure CMake
      run: >
        cmake -B ${{ steps.strings.outputs.build-output-dir }}
        -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        -S $GITHUB_WORKSPACE

    - name: Build
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }}

    - name: Test
      working-directory: ${{ steps.strings.outputs.build-output-dir }}
      run: |
        echo "# Type     Name     Full path to shared object file" > udpt
        echo "# ----     ----     -------------------------------" >> udpt
        echo "gxdisplay  Cairo    src/libgxdCairo.so" >> udpt
        echo "gxdisplay  X11      src/libgxdX11.so" >> udpt
        echo "gxdisplay  gxdummy  src/libgxdummy.so" >> udpt
        echo "*" >> udpt
        echo "gxprint    Cairo    src/libgxpCairo.so" >> udpt
        echo "gxprint    GD       src/libgxpGD.so" >> udpt
        echo "gxprint    gxdummy  src/libgxdummy.so" >> udpt

        GADDIR=data GAUDPT=udpt ./src/grads -l -b -c "quit"
